### ISSUE TITLE
Landing page is blank when logged in

### ISSUE THREAD

**Issue by WildWeazel** [naturenet/naturenet-android-app#1]
If a user session is active when the app starts, the landing page is completely blank. If the page is not relevant to logged in users then it should default to a different page.

**Comment by cameronjj** [comment]
Seems if I just quit the app (without logging out) and come back to it, it's also blank and it's automatically logged me out.

**Comment by akashungarala** [comment]
Displaying the activity before running the code. It is fixed now.
