### ISSUE TITLE
App stuck in "Loading" state if some data is missing

### ISSUE THREAD

**Issue by WildWeazel** [naturenet/naturenet-android-app#14]
If the data does not exist or does not meet expected format, show what you can and/or warn that it cannot be displayed

**Comment by WildWeazel** [comment]
Not sure is this is the same case as before, but it happens if you select a project with fewer observations than the number to show on the screen

**Comment by WildWeazel** [comment]
see also #15

**Comment by akashungarala** [comment]
Handled the condition checking for all the data that is retrieved before displaying.
