### ISSUE TITLE
App crashes when submitting observation if user is logged in from previous session

### ISSUE THREAD

**Issue by WildWeazel** [naturenet/naturenet-android-app#37]
When saving a new observation to the database the app tries to re-authenticate using stored credentials. If the user session was already active when the app started the credentials will not have been initialized locally.

**Comment by cameronjj** [comment]
I second this.  If I close the app and sign in again, it crashed on me (only for new photos -- not ones from my gallery).  However if I logged out the previous time and then logged back in, it works
