### ISSUE TITLE
Add distinction for open and closed projects

### ISSUE THREAD

**Issue by cameronjj** [naturenet/naturenet-android-app#43]
Native or Not is the first project that appears for me, but I can't contribute.  Maybe we should think of a way to filter or separate different projects.

**Comment by WildWeazel** [comment]
What's your site affiliation? We aren't (yet) enforcing any open/closed state but the new observation page uses site association to limit who can submit. Related to this issue for iOS: https://github.com/naturenet/naturenet_ios/issues/12

**Comment by cameronjj** [comment]
I think I'm zz_elsewhere.

**Comment by WildWeazel** [comment]
Until we decide how to present projects from other sites we've allowed anyone to submit to any project. Still need to think about visualizing site associations.

**Comment by WildWeazel** [comment]
For now these fields have been cleared in the database until we decide what they should mean. Apps show nothing for blank status.
