### ISSUE TITLE
Pressing back from some screens shows blank screen

### ISSUE THREAD

**Issue by WildWeazel** [naturenet/naturenet-android-app#57]
From Explore map, select a marker and touch the preview to bring up the observation detail page. Then press back button on the phone (not in action bar). Screen goes blank with "<< Explore" still shown in the action bar. Back again returns to the map.

**Comment by WildWeazel** [comment]
Same thing happens from New Observation screen

**Comment by WildWeazel** [comment]
Same on sign in page, but not join

**Comment by sabdella** [comment]
Seems fine when the back button on the app is used. It happens for me when using my phone back button

**Comment by sabdella** [comment]
I see this issue had been closed, but I just faced the same problem pressing the back button on the free observation page.

**Comment by WildWeazel** [comment]
2.0.1 isn't published yet
