### ISSUE TITLE
Can't get out of keyboard when adding a description to an observation

### ISSUE THREAD

**Issue by cameronjj** [naturenet/naturenet-android-app#59]
When I make and observation and click in the text box to add a description, I can't click out of it.  I need to get out of the app and then get reopen it to get the keyboard to disappear.  When the keyboard comes up, the send button also disappears, making it impossible to send.  It would be great to have a way to click out of the keyboard or at least not lose the send button.

![screenshot_20160914-113911](https://cloud.githubusercontent.com/assets/4220521/18560613/998be9c2-7b39-11e6-85e0-6b2a6ae6ff55.png)

**Comment by Kazjon** [comment]
This issue might be fixed int he current build?  @akashungarala will check to see whether it's still happening, and either close it or tag it as a bug based on what he finds.
