### ISSUE TITLE
Cannot submit a comment

### ISSUE THREAD

**Issue by cameronjj** [naturenet/naturenet-android-app#61]
Went into caterpillars project and then liz's photo.  Cannot click the "send" button to submit a comment.

**Comment by cameronjj** [comment]
And if I click on the like button, but then don't submit and have to go back, the like selection disappears

**Comment by WildWeazel** [comment]
Which build are you using?

**Comment by WildWeazel** [comment]
@cameronjj I can see that you were using an old build at some point recently. If this still happens after you update to 0.1.3 comment again and I'll reopen.
