### ISSUE TITLE
Add the camera/add observation button to each project page.

### ISSUE THREAD

**Issue by dara1429** [naturenet/naturenet-android-app#72]
Something i encountered using the app for the first time was when i was trying to add a downspout observation, i could not figure out where to add it. It took me a minute to realize the camera button on the main explore screen is used to add observations to any project. I think it would be nice to add a button on each project page (The top right corner of the screen on the screenshot below easily has room for this) to quickly add an observation to the project you are viewing.

![screenshot_20161030-122124](https://cloud.githubusercontent.com/assets/11980947/19838855/4cc7343e-9e9d-11e6-9148-118bcbd673c2.png)

**Comment by WildWeazel** [comment]
depends on #83

**Comment by WildWeazel** [comment]
Action buttons and dialogs are now implemented at the activity level, but only in MainActivity. The dialogs should belong to a reusable controller class that can be attached to any activity instead of including the views directly.

**Comment by rigotre7** [comment]
Implemented in release v2.3.1
