### ISSUE TITLE
Create an account menu has fields that cannot be tapped

### ISSUE THREAD

**Issue by Twake56** [naturenet/naturenet-android-app#73]
Testing app on samsung S5 running 6.0.1. The keyboard blocks all fields below "Name" and since the page is fixed size the "next" button is the only convenient way to get to the field below name.

![login1](https://cloud.githubusercontent.com/assets/16886123/19865044/48d439f8-9f60-11e6-9d70-912d89da46cc.png)

Once I have navigated to the email field the done button lowers the keyboard and I am free to select the affiliation field. The issue could quickly be fixed if the page could be scrolled up past its necessary length so the fields could be accessed in the space above the keyboard.

![login2](https://cloud.githubusercontent.com/assets/16886123/19865281/2e3b8866-9f61-11e6-9253-4f2e615d78c4.png)

**Comment by WildWeazel** [comment]
fixed in 0096b177d9009054676575e6bcdb251459ca5e7c
