### ISSUE TITLE
Downspout projects page completely non-functional

### ISSUE THREAD

**Issue by dmckinney5** [naturenet/naturenet-android-app#75]
https://scontent.fsnc1-5.fna.fbcdn.net/v/t34.0-12/14886097_10210190381178983_171149265_n.png?oh=4c291d76c1c6bbdc02f573083a863118&oe=581A2AC4

I am on an LG G5, and the entire downspout project page would not work on my device. That includes the back arrows, the 'send a comment' button and unless I missed it there was no option for me to contribute to the project. If there was an option to contribute and I just missed it, consider that it may be fairly easy to miss as I looked for a decent amount of time. No error messages/feedback was generated when I pressed these non functioning buttons

**Comment by WildWeazel** [comment]
see #70 #71 #72 for the individual problems
