### ISSUE TITLE
Pin/Post no longer there?

### ISSUE THREAD

**Issue by dbecker111** [naturenet/naturenet-android-app#76]
I commented (which also didn't work, but someone else has already created an issue) on a pin/post near where I live and when I went back to look at it an hour later or so, it was no longer there. 
I  had opened the app earlier, viewed and commented on an already existing post. When I came back into the app just now, the pin was not there. I looked into the website and it indeed was there, so there must be an issue with how the app populates the map. The first screenshot is the app at 4:57pm today and the second is the website around 5:10pm today. Unfortunately I don't have a screenshot from when the pin _was_ populated in the app ~3:00pm today.
![screenshot_2016-10-31-16-57-53](https://cloud.githubusercontent.com/assets/10735927/19874547/acec9982-9f8b-11e6-9110-4208dbad584a.png)

![screenshot](https://cloud.githubusercontent.com/assets/10735927/19874768/425f7b28-9f8d-11e6-9997-a9ced08ffc66.JPG)

**Comment by WildWeazel** [comment]
This is because the map is only loading the most recent observations, so as new ones are submitted older ones will fall out of view. See #82 for upcoming search by distance.
