### ISSUE TITLE
"Join NatureNet Today" button opens up multiple instances of sign up page

### ISSUE THREAD

**Issue by pillig** [naturenet/naturenet-android-app#78]
When opening an un-cached version of the app (i.e. first time opening), I found that the "Join NatureNet Today" button on the first page takes a while to bring up the sign up page. I wasn't sure if I had clicked it, so I pressed it a few more times. 
[http://imgur.com/a/nw6MA](http://imgur.com/a/nw6MA)
Eventually, the sign up page opened. I filled in the information and pressed "Join" and found that another login page was behind it. It turned out ~5 login pages had spawned, about the number of times I had clicked the "Join NatureNet Today" button. I was able to recreate the situation one more time by clearing NatureNet's cache. I found it hard to take a screenshot of this occurrence because of how fast the sign up page disappears. I will keep trying to get some screenshots of the exact problem.

I was running the app on Android 7.1 on a Pixel XL using CU's wi-fi.

Update: I have been unable to recreate this for a while. I believe this is mainly due to the fact I am no longer on the wi-fi that I was using when I first found this. I'm not completely sure, but it seems like the logon page needs an internet connection to open, so I'm guessing a bad connection is what is really needed to reproduce this.

**Comment by WildWeazel** [comment]
related to #68
