### ISSUE TITLE
Unable to figure out how to submit downspout observation

### ISSUE THREAD

**Issue by kedo8480** [naturenet/naturenet-android-app#79]
I was unable to figure out how to submit an observation of a downspout. I found the tabs and clicked "Projects". Then from the list of projects I clicked "Downspout". Then I was taken to this page with bunch of downspout observations. There was no way for me to submit a new one, though, and I looked for a long time trying to find a button that would allow me to add a downspout observation. This was on the Android application.
![screenshot_20161031-190756](https://cloud.githubusercontent.com/assets/14288007/19876719/6581255a-9f9e-11e6-98ea-cdbe4497b147.png)

**Comment by WildWeazel** [comment]
#72
